apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: accounts_service
  description: Microservice for handling account information.
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  system: Accounts
  lifecycle: production
  owner: accounts-team
  providesApis:
    - account_info_api
