apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: accounts_service
  description: Microservice for handling account information.
  annotations:
    backstage.io/techdocs-ref: dir:.
  appID: app-1
spec:
  type: service
  system: Accounts
  lifecycle: production
  owner: accounts-team
  providesApis:
    - account_info_api
  consumesApis:
    - GSP_api
  dependsOn: ['component:GSP','resource:mongodb-database']
