apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: GSP
  description: GSP
  appID: app-4
  tags:
    - java
spec:
  type: service
  system: Accounts
  lifecycle: production
  owner: gsp_team
  providesApis:
   - GSP_api
