apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: accounts_statement_service
  description: Handling Accounts Statments
spec:
  type: service
  system: Accounts
  lifecycle: production
  owner: accounts-team
