apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: accounts_statement_service
  description: Handling Accounts Statmentsf
  appID: app-5
spec:
  type: service
  system: Accounts
  lifecycle: production
  owner: accounts-team
